// DSH-16 — maps a goal to one of the four body-diagram assets generated by
// scripts/gen-today-assets.mjs. Phase 4 (DSH-18) renders these in the /today GoalList.
//
// Client-safe: takes a structural subset of `Goal` (no Drizzle/server imports) so it
// can run in a client component. Picks an intent from the measurable target direction
// first, then falls back to keywords in the title.

export type GoalIntent =
  | "fat-loss"
  | "muscle-gain"
  | "recomp"
  | "maintenance";

export type GoalDiagram = {
  intent: GoalIntent;
  /** Public path to the transparent body-diagram PNG. */
  src: string;
  /** Short human label for alt text / captions. */
  label: string;
};

const DIAGRAMS: Record<GoalIntent, GoalDiagram> = {
  "fat-loss": {
    intent: "fat-loss",
    src: "/today/goal-fat-loss.png",
    label: "Fat loss",
  },
  "muscle-gain": {
    intent: "muscle-gain",
    src: "/today/goal-muscle-gain.png",
    label: "Muscle gain",
  },
  recomp: {
    intent: "recomp",
    src: "/today/goal-recomp.png",
    label: "Recomposition",
  },
  maintenance: {
    intent: "maintenance",
    src: "/today/goal-maintenance.png",
    label: "Maintenance",
  },
};

/** The brand hero figure (header), also generated by the Phase 2 pipeline. */
export const HERO_FIGURE_SRC = "/today/hero-figure.png";

// DSH-21 — gender hero silhouettes (replace the photographic hero-figure).
export const HERO_MALE_SRC = "/today/hero-male.png";
export const HERO_FEMALE_SRC = "/today/hero-female.png";

export type HeroFigure = "male" | "female" | "custom" | null | undefined;
export type Sex = "male" | "female" | null | undefined;

export type ResolvedHero = {
  /** Public/Blob image URL to render in the header. */
  src: string;
  /** "figure" = a built-in silhouette cutout; "custom" = a user photo. */
  kind: "figure" | "custom";
  /** The effective figure choice (for highlighting the active option in the UI). */
  effective: "male" | "female" | "custom";
};

/**
 * Resolve which header image to show. An explicit choice wins; otherwise the
 * default is derived from the user's sex (from Chad's memory), falling back to
 * the male silhouette. A "custom" choice with no stored URL falls back too.
 */
export function resolveHero(
  heroFigure: HeroFigure,
  heroImageUrl: string | null | undefined,
  sex: Sex
): ResolvedHero {
  if (heroFigure === "custom" && heroImageUrl) {
    return { src: heroImageUrl, kind: "custom", effective: "custom" };
  }
  const explicit = heroFigure === "male" || heroFigure === "female";
  const figure: "male" | "female" = explicit
    ? (heroFigure as "male" | "female")
    : sex === "female"
      ? "female"
      : "male";
  return {
    src: figure === "female" ? HERO_FEMALE_SRC : HERO_MALE_SRC,
    kind: "figure",
    effective: figure,
  };
}

/** Map a free-text "Sex" memory value to a normalized sex, or null. */
export function normalizeSex(raw: string | null | undefined): Sex {
  if (!raw) {
    return null;
  }
  const v = raw.trim().toLowerCase();
  if (/^(f|female|woman|girl|w)\b/.test(v)) {
    return "female";
  }
  if (/^(m|male|man|boy)\b/.test(v)) {
    return "male";
  }
  return null;
}

export function diagramForIntent(intent: GoalIntent): GoalDiagram {
  return DIAGRAMS[intent];
}

type GoalLike = {
  title?: string | null;
  metric?: "weight" | "bodyfat" | "measurement" | "custom" | null;
  startValue?: number | null;
  targetValue?: number | null;
};

const LOSS_WORDS =
  /\b(lose|loss|losing|cut(ting)?|lean|shred|slim|drop|trim|deficit|fat[- ]?loss)\b/i;
const GAIN_WORDS =
  /\b(gain|bulk(ing)?|build|grow|mass|muscle|size|bigger|strength|strong)\b/i;
const RECOMP_WORDS = /\b(recomp|recomposition|tone|toned|body[- ]?recomp)\b/i;
const MAINTAIN_WORDS = /\b(maintain|maintenance|hold|sustain|keep)\b/i;

/**
 * Choose a goal body diagram. Measurable direction wins (a weight/bodyfat target
 * moving down = fat loss, up = muscle gain); otherwise infer from the title; default
 * to recomposition (the balanced figure) when nothing is decisive.
 */
export function goalDiagram(goal: GoalLike): GoalDiagram {
  const { metric, startValue, targetValue, title } = goal;

  // 1) Measurable direction — the strongest signal.
  const hasRange =
    typeof startValue === "number" && typeof targetValue === "number";
  if (hasRange && startValue !== targetValue) {
    const goingDown = (targetValue as number) < (startValue as number);
    if (metric === "weight" || metric === "bodyfat") {
      return DIAGRAMS[goingDown ? "fat-loss" : "muscle-gain"];
    }
    // A body measurement (e.g. arms up = gain, waist down = loss). Without knowing
    // which spot, fall through to title keywords below.
  }

  // 2) Title keywords.
  const t = title ?? "";
  if (RECOMP_WORDS.test(t)) return DIAGRAMS.recomp;
  if (MAINTAIN_WORDS.test(t)) return DIAGRAMS.maintenance;
  const loss = LOSS_WORDS.test(t);
  const gain = GAIN_WORDS.test(t);
  if (loss && !gain) return DIAGRAMS["fat-loss"];
  if (gain && !loss) return DIAGRAMS["muscle-gain"];

  // 3) Default — the balanced figure reads as "general progress".
  return DIAGRAMS.recomp;
}
